name: ci

# This pipeline is intended to facilitate the full coverage of tests for OSS GX.
# A "reasonable" set of tests will run on every pull request, and a full set will run with:
#   1. Manual triggering
#   2. Every 3 hours
#   3. When we push a tag with a semver pattern x.y.z (for example 0.0.1) which is the pattern we use for releases.

env:
  ECR_PULL_THROUGH_REPOSITORY_URL: 258143015559.dkr.ecr.us-east-1.amazonaws.com/docker-hub/

on:
  merge_group:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  schedule:
    # https://crontab.guru/every-3-hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # allows manual triggering with branch picker
  push:
    # Semantic versioning syntax defined by PyPI: https://pythonpackaging.info/07-Package-Release.html#Versioning-your-code
    tags:
      # Stable release syntax
      - "[0-9]+.[0-9]+.[0-9]+"
      # Prerelease syntax
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  marker-tests:
    env:
      GX_PYTHON_EXPERIMENTAL: true # allow for python 3.13+
      # google
      GE_TEST_GCP_CREDENTIALS: ${{secrets.GE_TEST_GCP_CREDENTIALS}}
      GE_TEST_GCP_PROJECT: ${{secrets.GE_TEST_GCP_PROJECT}}
      GE_TEST_BIGQUERY_DATASET: ${{secrets.GE_TEST_BIGQUERY_DATASET}}
      GOOGLE_APPLICATION_CREDENTIALS: "gcp-credentials.json"
      # aws
      AWS_ACCESS_KEY_ID: ${{secrets.CI_AWS_ACCESS_KEY_ID}}
      AWS_DEFAULT_REGION: ${{secrets.CI_AWS_DEFAULT_REGION}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.CI_AWS_SECRET_ACCESS_KEY}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_SQL_TOKEN}}
      DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
      DATABRICKS_HTTP_PATH: ${{secrets.DATABRICKS_HTTP_PATH}}

      # snowflake
      SNOWFLAKE_CI_ACCOUNT: ${{secrets.SNOWFLAKE_CI_ACCOUNT}}
      SNOWFLAKE_CI_USER_PASSWORD: ${{secrets.SNOWFLAKE_CI_USER_PASSWORD}}
      SNOWFLAKE_ACCOUNT: ${{secrets.SNOWFLAKE_ACCOUNT}}
      SNOWFLAKE_USER: ${{secrets.SNOWFLAKE_USER}}
      SNOWFLAKE_PW: ${{secrets.SNOWFLAKE_PW}}
      SNOWFLAKE_DATABASE: ${{secrets.SNOWFLAKE_DATABASE}}
      SNOWFLAKE_SCHEMA: ${{secrets.SNOWFLAKE_SCHEMA}}
      SNOWFLAKE_WAREHOUSE: ${{secrets.SNOWFLAKE_WAREHOUSE}}
      SNOWFLAKE_ROLE: ${{secrets.SNOWFLAKE_ROLE}}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        markers:
          - snowflake
          - postgresql
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        exclude:
          # TODO: would like to adopt `actionlint` pre-commit hook
          # but false positive here and inability to do an inline ignore
          # prevents this https://github.com/rhysd/actionlint/issues/237
          - python-version: ${{ github.event_name == 'pull_request_target' && '3.10' }}
          - python-version: ${{ github.event_name == 'pull_request_target' && '3.11' }}
          - python-version: ${{ github.event_name == 'merge_group' && '3.10' }}
          - python-version: ${{ github.event_name == 'merge_group' && '3.11' }}
          - python-version: ${{ github.event_name == 'workflow_dispatch' && '3.10' }}
          - python-version: ${{ github.event_name == 'workflow_dispatch' && '3.11' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Upgrade Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            reqs/requirements-dev-test.txt
            setup.py

      - name: Copy GCP credentials to file
        run: |
          echo "$GE_TEST_GCP_CREDENTIALS" > gcp-credentials.json

      - name: Install dependencies
        run: |
          pip install $(grep -E '^(invoke)' reqs/requirements-dev-contrib.txt)
          invoke deps --gx-install -m '${{ matrix.markers }}' -r test

      - name: Install mssql odbc driver
        run: ./scripts/install_mssql_odbc_driver.sh

      - name: Configure ECR AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::258143015559:role/github-amazonec2containerregistryreadonly

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run the tests
        run: invoke ci-tests '${{ matrix.markers }}' --up-services --verbose  --reports

      # upload coverage report to codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: great-expectations/great_expectations
          flags: "${{ matrix.python-version }} ${{ matrix.markers }}"

      # upload test results to codecov
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: "${{ matrix.python-version }} ${{ matrix.markers }}"
